version: '2'
services:

  sldap:
    image: osixia/openldap:1.5.0
    container_name: sldap
    hostname: sldap
    ports:
    - "389:389"
    - "636:636"
    environment:
      LDAP_ORGANISATION: home-local
      LDAP_DOMAIN: home.local
      LDAP_ADMIN_PASSWORD: password
      LDAP_CONFIG_PASSWORD: password
      LDAP_RFC2307BIS_SCHEMA: 'true'
      LDAP_TLS_VERIFY_CLIENT: never
      LDAP_REMOVE_CONFIG_AFTER_SETUP: 'true'
    command: ["--copy-service","--loglevel=debug"]
    volumes:
    - ./resources/ldap-ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom

  skeycloak:
    container_name: skeycloak
    hostname: skeycloak
    image: quay.io/keycloak/keycloak:21.0.1
    ports:
    - 9080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command: [ "start-dev", "--import-realm" ]
    volumes:
    - ./resources/realms:/opt/keycloak/data/import
    depends_on:
    - sldap

  ssplunk:
    image: splunk/splunk:8.2.6
    container_name: ssplunk
    hostname: ssplunk
    ports:
    - "9000:8000"
    - "9089:8089"
    - "9088:8088"
    environment:
      SPLUNK_DISABLE_POPUPS: "true"
      LANG: en_US.utf8
      SPLUNK_ROLE: splunk_standalone
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: password
      SPLUNK_HEC_TOKEN: password
    volumes:
    - ./resources/splunk/splunk-etc/auth/scripts/SAML_script_keycloak.py:/opt/splunk-etc/auth/scripts/SAML_script_keycloak.py:ro
    - ./resources/splunk/splunk-etc/auth/splunksaml.pem:/opt/splunk-etc/auth/splunksaml.pem:ro
    - ./resources/splunk/splunk-etc/auth/idpCerts:/opt/splunk-etc/auth/idpCerts:ro
    - ./resources/splunk/splunk-etc/system/local/authentication.conf:/opt/splunk-etc/system/local/authentication.conf:ro
    depends_on:
    - skeycloak
