version: '3.4'

networks:
  default:
    external:
      name: apps

services:

  sbs:
    image: local/splunk:8.1.3
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 8.1.3
        TOOL: splunk
    container_name: sbs
    hostname: sbs
    ports:
    - "8000:8000"
    - "8089:8089"
    environment:
      SPLUNK_DISABLE_POPUPS: "true"
      LANG: en_US.utf8
      SPLUNK_ROLE: splunk_standalone
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: password
    volumes:
    - ${HOME}/projects:/projects
  
  sbf:
    image: local/universalforwarder:8.1.3
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 8.1.3
        TOOL: universalforwarder
    container_name: sbf
    hostname: sbf
    environment:
      LANG: en_US.utf8
      SPLUNK_ROLE: splunk_universal_forwarder
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_INDEXER_URL: sbs
      SPLUNK_PASSWORD: password
    volumes:
    - ${HOME}/projects:/projects
