version: '2'
services:

  okeycloak:
    container_name: okeycloak
    hostname: okeycloak
    image: quay.io/keycloak/keycloak:21.0.1
    ports:
    - 8443:8443
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command:
    - start
    - --hostname=localhost
    - --https-key-store-file=/opt/keystore/conf/keystore.p12
    - --https-key-store-password=password
    - --https-trust-store-file=/opt/keystore/conf/truststore.p12
    - --https-trust-store-password=password
    - --https-client-auth=request
    - --import-realm
    volumes:
    - ./certs/keystore.p12:/opt/keystore/conf/keystore.p12
    - ./certs/truststore.p12:/opt/keystore/conf/truststore.p12
    - ./resources/realms:/opt/keycloak/data/import
    depends_on:
    - oldap

  osplunk:
    image: splunk/splunk:8.2.6
    container_name: osplunk
    hostname: osplunk
    ports:
    - "8000:8000"
    - "8089:8089"
    environment:
      SPLUNK_DISABLE_POPUPS: "true"
      LANG: en_US.utf8
      SPLUNK_ROLE: splunk_standalone
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: password
      SPLUNK_HEC_TOKEN: password
    volumes:
    - ./resources/splunk/splunk-etc/system/local/authorize.conf:/opt/splunk-etc/system/local/authorize.conf
    - ./resources/splunk/splunk-etc/system/local/authentication.conf:/opt/splunk-etc/system/local/authentication.conf
    depends_on:
    - oldap

  oproxy:
    image: httpjwt:latest
    container_name: oproxy
    hostname: oproxy
    ports:
    - 9000:9000
    volumes:
    - ./resources/apache-conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - ./resources/apache-conf/rs256:/usr/local/apache2/conf/rs256
    - ./resources/apache-conf/tokens:/usr/local/apache2/conf/tokens
    depends_on:
    - osplunk
    - okeycloak

  oldap:
    image: osixia/openldap:1.5.0
    container_name: oldap
    hostname: oldap
    ports:
    - "389:389"
    - "636:636"
    environment:
      LDAP_ORGANISATION: home-local
      LDAP_DOMAIN: home.local
      LDAP_ADMIN_PASSWORD: password
      LDAP_CONFIG_PASSWORD: password
      LDAP_RFC2307BIS_SCHEMA: 'true'
      LDAP_TLS_VERIFY_CLIENT: never
      LDAP_REMOVE_CONFIG_AFTER_SETUP: 'true'
    command: ["--copy-service","--loglevel=debug"]
    volumes:
    - ./resources/ldap-ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom

volumes:
  okeycloak_data:
    driver: local

