version: '3.4'

networks:
  default:
    external:
      name: apps

services:

  sh-lb:
    image: haproxy:2.3
    container_name: sh-lb
    hostname: sh-lb
    depends_on:
    - sh1
    - sh2
    - sh3
    expose:
    - "8000"
    - "8089"
    ports:
    - "8200:8000"
    - "8289:8089"
    volumes:
    - ./haproxy:/usr/local/etc/haproxy
  
  deployer:
    image: local/splunk:8.1.3
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 8.1.3
        TOOL: splunk
    container_name: deployer
    hostname: deployer
    environment:
      LANG: en_US.utf8
      SPLUNK_PASSWORD: password
      SPLUNK_DISABLE_POPUPS: "true"
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ROLE: splunk_deployer
      SPLUNK_DEPLOYER_URL: deployer
      SPLUNK_CLUSTER_MASTER_URL: cm1
      SPLUNK_SHC_LABEL: docker_shc
      SPLUNK_SHC_PASS4SYMMKEY: sh_comms
      SPLUNK_IDXC_DISCOVERYPASS4SYMMKEY: cm_and_forwarder_comms
    volumes:
    - ${HOME}/projects:/projects
    
  sh1:
    depends_on:
    - deployer
    image: local/splunk:8.1.3
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 8.1.3
        TOOL: splunk
    container_name: sh1
    hostname: sh1
    environment:
      LANG: en_US.utf8
      SPLUNK_PASSWORD: password
      SPLUNK_DISABLE_POPUPS: "true"
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ROLE: splunk_search_head
      SPLUNK_SEARCH_HEAD_CAPTAIN_URL: sh1
      SPLUNK_SEARCH_HEAD_URL: sh1,sh2,sh3
      SPLUNK_DEPLOYER_URL: deployer
      SPLUNK_CLUSTER_MASTER_URL: cm1
      SPLUNK_SHC_LABEL: docker_shc
      SPLUNK_SHC_PASS4SYMMKEY: sh_comms
      SPLUNK_IDXC_PASS4SYMMKEY: cm_and_indexer_comms
      SPLUNK_IDXC_DISCOVERYPASS4SYMMKEY: cm_and_forwarder_comms
    volumes:
    - ${HOME}/projects:/projects

  sh2:
    depends_on:
    - deployer
    image: local/splunk:8.1.3
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 8.1.3
        TOOL: splunk
    container_name: sh2
    hostname: sh2
    environment:
      LANG: en_US.utf8
      SPLUNK_PASSWORD: password
      SPLUNK_DISABLE_POPUPS: "true"
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ROLE: splunk_search_head
      SPLUNK_SEARCH_HEAD_CAPTAIN_URL: sh1
      SPLUNK_SEARCH_HEAD_URL: sh1,sh2,sh3
      SPLUNK_DEPLOYER_URL: deployer
      SPLUNK_CLUSTER_MASTER_URL: cm1
      SPLUNK_SHC_LABEL: docker_shc
      SPLUNK_SHC_PASS4SYMMKEY: sh_comms
      SPLUNK_IDXC_PASS4SYMMKEY: cm_and_indexer_comms
      SPLUNK_IDXC_DISCOVERYPASS4SYMMKEY: cm_and_forwarder_comms
    volumes:
    - ${HOME}/projects:/projects

  sh3:
    depends_on:
    - deployer
    image: local/splunk:8.1.3
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 8.1.3
        TOOL: splunk
    container_name: sh3
    hostname: sh3
    environment:
      LANG: en_US.utf8
      SPLUNK_PASSWORD: password
      SPLUNK_DISABLE_POPUPS: "true"
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ROLE: splunk_search_head
      SPLUNK_SEARCH_HEAD_CAPTAIN_URL: sh1
      SPLUNK_SEARCH_HEAD_URL: sh1,sh2,sh3
      SPLUNK_DEPLOYER_URL: deployer
      SPLUNK_CLUSTER_MASTER_URL: cm1
      SPLUNK_SHC_LABEL: docker_shc
      SPLUNK_SHC_PASS4SYMMKEY: sh_comms
      SPLUNK_IDXC_PASS4SYMMKEY: cm_and_indexer_comms
      SPLUNK_IDXC_DISCOVERYPASS4SYMMKEY: cm_and_forwarder_comms
    volumes:
    - ${HOME}/projects:/projects

