version: '3.4'

networks:
  default:
    external:
      name: apps

services:

  cm1:
    image: local/splunk:8.2.6
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 8.2.6
        TOOL: splunk
    container_name: cm1
    hostname: cm1
    ports:
    - "8100:8000"
    - "8189:8089"
    environment:
      LANG: en_US.utf8
      SPLUNK_PASSWORD: password
      SPLUNK_DISABLE_POPUPS: "true"
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ROLE: splunk_cluster_master
      SPLUNK_CLUSTER_MASTER_URL: cm1
      SPLUNK_IDXC_REPLICATION_FACTOR: 2
      SPLUNK_IDXC_SEARCH_FACTOR: 2
      SPLUNK_IDXC_LABEL: docker_idx
      SPLUNK_IDXC_PASS4SYMMKEY: cm_and_indexer_comms
      SPLUNK_IDXC_DISCOVERYPASS4SYMMKEY: cm_and_forwarder_comms
    volumes:
    - ${HOME}/projects:/projects
 
  idx1-1: 
    image: local/splunk:8.2.6
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 8.2.6
        TOOL: splunk
    container_name: idx1-1
    hostname: idx1-1
    environment:
      LANG: en_US.utf8
      SPLUNK_PASSWORD: password
      SPLUNK_DISABLE_POPUPS: "true"
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ROLE: splunk_indexer
      SPLUNK_CLUSTER_MASTER_URL: cm1
      SPLUNK_IDXC_PASS4SYMMKEY: cm_and_indexer_comms
    volumes:
    - ${HOME}/projects:/projects

  idx1-2: 
    image: local/splunk:8.2.6
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 8.2.6
        TOOL: splunk
    container_name: idx1-2
    hostname: idx1-2
    environment:
      LANG: en_US.utf8
      SPLUNK_PASSWORD: password
      SPLUNK_DISABLE_POPUPS: "true"
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ROLE: splunk_indexer
      SPLUNK_CLUSTER_MASTER_URL: cm1
      SPLUNK_IDXC_PASS4SYMMKEY: cm_and_indexer_comms
    volumes:
    - ${HOME}/projects:/projects
