version: '3.4'

networks:
  default:
    external:
      name: apps

services:

  sh1:
    image: local/splunk:8.2.6
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 8.2.6
        TOOL: splunk
    container_name: hf1
    hostname: hf1
    ports:
    - "8300:8000"
    - "8389:8089"
    environment:
      LANG: en_US.utf8
      SPLUNK_PASSWORD: password
      SPLUNK_DISABLE_POPUPS: "true"
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ROLE: splunk_heavy_forwarder
      SPLUNK_CLUSTER_MASTER_URL: cm1
      SPLUNK_IDXC_PASS4SYMMKEY: cm_and_indexer_comms
      SPLUNK_IDXC_DISCOVERYPASS4SYMMKEY: cm_and_forwarder_comms
    volumes:
    - ${HOME}/projects:/projects
